# Generated by Django 2.2.19 on 2021-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('task_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='Date of task created.')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('playbook_path', models.CharField(default='/etc/ansible/', max_length=100)),
                ('playbook_name', models.CharField(default='default.yml', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAppMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0)),
                ('task_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHostMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('task_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('result_content', models.TextField()),
                ('started_at', models.DateTimeField(verbose_name='Datetime of the task startup.')),
                ('end_at', models.DateTimeField(verbose_name='Datetime of the task stop.')),
            ],
        ),
        migrations.CreateModel(
            name='TaskServiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('service_id', models.IntegerField(default=0)),
            ],
        ),
    ]
