# Generated by Django 2.2.19 on 2021-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Date of task created.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_method',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taskansible',
            name='task_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskappmapping',
            name='app_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskappmapping',
            name='task_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskhostmapping',
            name='host_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskhostmapping',
            name='task_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskrunresult',
            name='end_at',
            field=models.DateTimeField(db_index=True, verbose_name='Datetime of the task stop.'),
        ),
        migrations.AlterField(
            model_name='taskrunresult',
            name='started_at',
            field=models.DateTimeField(db_index=True, verbose_name='Datetime of the task startup.'),
        ),
        migrations.AlterField(
            model_name='taskrunresult',
            name='status',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taskrunresult',
            name='task_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskservicemapping',
            name='service_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskservicemapping',
            name='task_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
