# Generated by Django 2.2.19 on 2021-04-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('comment', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureCheckPointMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(db_index=True)),
                ('checkpoint_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('check_point_id', models.IntegerField()),
                ('steps', models.CharField(max_length=500)),
                ('excepted_result', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseTaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True)),
                ('case_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(default='None', max_length=20)),
                ('run_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('comment', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('progress', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
