# Generated by Django 2.2.19 on 2021-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationport',
            name='app_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='applicationport',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationport',
            name='port',
            field=models.IntegerField(db_index=True),
        ),
    ]
