# Generated by Django 2.2.19 on 2021-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(verbose_name='Date of host created.')),
            ],
        ),
        migrations.CreateModel(
            name='HostAppMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('app_id', models.IntegerField(default=0)),
                ('app_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HostBaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('cpu_core', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostLoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('login_method', models.CharField(max_length=100)),
                ('login_port', models.IntegerField()),
                ('login_user', models.CharField(max_length=100)),
                ('login_password', models.CharField(max_length=100, null=True)),
                ('login_key', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('network_type', models.CharField(max_length=10)),
                ('network_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostServiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('service_id', models.IntegerField(default=0)),
                ('service_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HostStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=0)),
                ('storage_type', models.CharField(max_length=50)),
                ('storage_size', models.IntegerField()),
            ],
        ),
    ]
