# Generated by Django 2.2.19 on 2021-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_shot', models.CharField(max_length=100)),
                ('operation_detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OperationAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('operation_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='Date of the audit log created.')),
            ],
        ),
    ]
