# Generated by Django 2.2.19 on 2021-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaudit',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Date of the audit log created.'),
        ),
        migrations.AlterField(
            model_name='operationaudit',
            name='operation_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='operationaudit',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
