# Generated by Django 2.2.19 on 2021-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userrolemapping',
            name='role_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userrolemapping',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
